services:
  ph-eye:
    image: philterd/ph-eye:1.2.1
    ports:
      - "18080:5000"
    networks:
      - philter
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
  philter:
    depends_on:
      - ph-eye
    build:
      context: .
      dockerfile: Dockerfile.philter
    ports:
      - "8080:8080"
    volumes:
      - ./distribution/philter.properties:/opt/philter/philter.properties
      - ./distribution/indexes/:/opt/philter/indexes/
      - ./distribution/policies/:/opt/philter/policies/
    networks:
      - philter
  philter-ui:
    depends_on:
      - philter
    build:
      context: .
      dockerfile: Dockerfile.philter-ui
    ports:
      - "9000:9000"
    volumes:
      - ./distribution/philter-ui.properties:/opt/philter/philter-ui.properties
    networks:
      - philter
networks:
  philter:
