services:
  philter-ner:
    image: philterd/philter-ner:2.5.0-general-lite-3.0
    ports:
      - "8000:18080"
    networks:
      - philter
  philter:
    depends_on:
      - philter-ner
    image: philterd/philter:2.5.0
    ports:
      - "8080:8080"
    networks:
      - philter
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
  philter-ui:
    depends_on:
      - philter-ner
      - philter
    image: philterd/philter-ui:2.5.0
    ports:
      - "9000:9000"
    networks:
      - philter
networks:
  philter:
