services:
  ph-eye:
    image: philterd/ph-eye:1.1.0
    ports:
      - "18080:5000"
    networks:
      - philter
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
  philter:
    depends_on:
      - ph-eye
    image: philterd/philter:2.7.0
    ports:
      - "8080:8080"
    volumes:
      - ./distribution/philter.properties:/opt/philter/philter.properties
      - ./distribution/indexes/:/opt/philter/indexes/
      - ./distribution/policies/:/opt/philter/policies/
    networks:
      - philter
  philter-ui:
    depends_on:
      - philter
    image: philterd/philter-ui:2.7.0
    ports:
      - "9000:9000"
    networks:
      - philter
networks:
  philter:
